export const WS_HOSTNAME = import.meta.env.VITE_WS_HOSTNAME
export const MULTIPLAYER_SET_ALL_PLAYERS_AS_SERVER_CONTROLLED =
  import.meta.env.VITE_MULTIPLAYER_SET_ALL_PLAYERS_AS_SERVER_CONTROLLED ===
  'true'
