#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

changed_files="$(git diff-tree -r --name-only --no-commit-id ORIG_HEAD HEAD)"
check_run() {
    if echo "$changed_files" | grep -q "$1"; then
        echo "🦄 Найдено изменение в $1, переустанавливаем зависимости..."
        eval "$2"
    else
        echo "✨ В $1 нет изменений, не будем переустанавливать зависимости"
    fi
}

check_run package.json "yarn && yarn lerna bootstrap"
check_run packages/shared "yarn shared:build"
check_run packages/engine "yarn shared:build"